services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173" # Map container's 5173 to host's 3000
    volumes:
      - .:/app
      - /app/node_modules # Prevents local node_modules from mounting
    environment:
      - NODE_ENV=development
    networks:
      app_net:
        aliases:
          - myreactapp

networks:
  app_net:
    name: app_network
